#!/usr/bin/env php
<?php


require __DIR__ . '/vendor/autoload.php';
use Illuminate\Database\Capsule\Manager as Capsule;
use Symfony\Component\Console\Application;
use Dotenv\Dotenv;
use app\Providers\DotenvServiceProvider;




require_once __DIR__ . '/commands/SetupCommand.php';
require_once __DIR__ . '/commands/MigrationCommand.php';
require_once __DIR__ . '/commands/ModelCommand.php';
require_once __DIR__ . '/commands/MakeEnvCommand.php';
require_once __DIR__ . '/commands/ControllerCommand.php';


$app = new Application('WHMCS Addon Framework', '1.0.0');
$app->add(new MakeEnvCommand()); 
$app->add(new SetupCommand());
$app->add(new MigrationCommand());
$app->add(new ModelCommand()); 
$app->add(new ControllerCommand());
$app->run();



$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

DatabaseServiceProvider::boot();



