#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
require_once __DIR__ . '/commands/SetupCommand.php';

$app = new Application('WHMCS Addon Framework', '1.0.0');
$app->add(new SetupCommand());
$app->run();
