#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Dotenv\Dotenv;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

// Load commands
require_once __DIR__ . '/commands/SetupCommand.php';
require_once __DIR__ . '/commands/MigrationCommand.php';
require_once __DIR__ . '/commands/ModelCommand.php'; // New Command

$app = new Application('WHMCS Addon Framework', '1.0.0');
$app->add(new SetupCommand());
$app->add(new MigrationCommand());
$app->add(new ModelCommand()); // Add Model Command
$app->run();
